Niestety nie zdążyłem zająć się wyglądem strony.

Funkcjonalność prawie cała jest napisana, z wyjątkiem requesta do tworzenia nowego REVIEW.
Nie udało mi się stworzyć odpowiedniego formatu dla body, natomiast cały mechanizm jest stworzony.
Nie udało mi się wysłać tego requesta nawet z api na stronie 'https://demo.h88.dev/'.

Wszystkie commity są na moim repozytorium pod adresem : https://github.com/franiczio/books.git


Dziękuję za zadanie, te parę dni było przyjemną zabawą z React+Redux :)
Mam nadzieję, że do zobacznia.

